### ISSUE TITLE
404 error when accessing "http://rpms.adiscon.com/v8-stable-daily/rsyslog-daily.repo"

### ISSUE THREAD

**Issue by wanghaopu** [rsyslog/rsyslog-pkg-rhel-centos#143]
This issue happens again now. Please check, thanks.

              It was a glitch an in a cleanup process. The source is identified and will be mitigated. The repo definition files are online again.

_Originally posted by @rgerhards in https://github.com/rsyslog/rsyslog-pkg-rhel-centos/issues/139#issuecomment-1842688607_

**Comment by alorbach** [comment]
I am sorry for the delay, the issue should be fixed now.

**Comment by crankedguy** [comment]
@alorbach Hi, this seems to be still an issue, I just realized on one of my servers that this is the case since June, 25th

Errors during downloading metadata for repository 'rsyslog_v8':
  - Status code: 404 for https://rpms.adiscon.com/v8-stable-daily/epel-9/x86_64/repodata/repomd.xml (IP: 45.55.202.239)
Error: Failed to download metadata for repo 'rsyslog_v8': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by alorbach** [comment]
Long story short, support for CentOS 7 has been dropped recently and the daily packages did not build because of this. The auto cleanup process removed the xml files (will not happen again) because they were not updated anymore. 

I have fixed the problem, rebuild the daily packages and uploaded the missing files. 
The daily packages should be working again, please let me know if you experience any further problems.
